site_name: Shopl 컨벤션
theme: readthedocs
nav:
  - 일러두기: index.md
  - Java:
      - 공통: java/common.md
      - 추천습관: java/habit.md
      - 메서드: java/method.md
      - Controller: java/controller.md
      - Service: java/service.md
      - DTO: java/dto.md
      - 에러 처리: java/error.md
      - 테스트 코드: java/test.md
